### ISSUE TITLE
Posso usar livremente?

### ISSUE THREAD

**Issue by brunocorbetta** [andrersp/controleEstoque#11]
Boa Noite.

Estou aprendendo python e gostei do seu programa, eu tenho uma pequena loja (pequena mesmo), e gostaria de ir testando e usando e aprendendo kkkkkk, posso usar para isso?

**Comment by andrersp** [comment]
Pode sim.. Não há restrição alguma de uso.

**Comment by Lucasrei9** [comment]
Pode sim

Em Sáb, 19 de dez de 2020 23:54, André Luis França <notifications@github.com>
escreveu:
