### ISSUE TITLE
Cara vendendo  teu sistema

### ISSUE THREAD

**Issue by misaelbr** [andrersp/controleEstoque#17]
https://www.facebook.com/groups/608492105999336/user/100065784783882/?__cft__[0]=AZUQaBtYecbm7S2N08u9AbxN20-MMoWBqXCdkvRpfTui4Uamot7jZMV_t23XnkkolocGQIpBh6t5MV4iU4OG9brM2-ge0dFXS5CAdYgQBgO_Q2Z5Ny8ZhaKIK0geVB7Q5etjDIvjHTh9cxEYqUNxK-2-cmn6QjEofsz2_XtjwPKfU1RhaZgSRYzVEZCAzW8m4U4&__tn__=%2CP-R

Perfil do cidadão: https://www.facebook.com/daniel.colpo.528
###

**Comment by andrersp** [comment]
Opa.. irei verificar.. Obrigado!

**Comment by luiz-fischer** [comment]
Rapaz o cara tá vendendo seu sistema em vários grupos como se fosse dele. Está rolando a umas duas semana já, já vi em 3 grupos diferentes do Facebook. Não sei se pra vc está tudo bem pois a licença está MIT mas é muita falta de ética.

**Comment by andrersp** [comment]
Se tiver como me envie um link por favor. No link acima já havia sido removido. 

Não me importo que vendam mas que aí menos contribua com o código caso tenha feito alguma melhoria.

**Comment by misaelbr** [comment]
Depois que tu me respondeu aqui, fui ver e já não estava mais lá o material.
Mas em resumo, o cara não se deu nem ao trabalho de mudar as prints... 

Queria ter capturado tela, mas aqui não tem como postar print.

**Comment by andrersp** [comment]
Já achei. Já tá resolvido e o anúncio já foi removido. Obrigado ai pela informação amigo.
